// app/layout.js
import "./globals.css";

export const metadata = {
  title: "Universal JSON Formatter - Professional API Testing Tool",
  description: "Advanced API testing and JSON formatting tool with headers, authentication, and request body support",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-sans bg-gradient-to-br from-black via-gray-900 to-gray-800">
        <main className="flex-grow flex items-start justify-center px-4">
          {children}
        </main>
      </body>
    </html>
  );
}










// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen flex flex-col font-sans bg-gradient-to-br from-black via-gray-900 to-gray-800">
//         <main className="flex-grow flex items-start justify-center px-4">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }








// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/header/index";
// import Footer from "@/components/footer/index";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen flex flex-col font-sans bg-gradient-to-br from-black via-gray-900 to-gray-800">
    
//         <main className="flex-grow flex items-start justify-center px-4">
//           {children}
//         </main>
     
//       </body>
//     </html>
//   );

// }
