import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-sans bg-gradient-to-br from-black via-gray-900 to-gray-800">
        <main className="flex-grow flex items-start justify-center px-4">
          {children}
        </main>
      </body>
    </html>
  );
}





